# Generated by Django 4.2.6 on 2023-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CIVILITY", models.CharField(max_length=40)),
                ("FIRST_NAME", models.CharField(max_length=40)),
                ("LAST_NAME", models.CharField(max_length=40)),
                ("EMAIL", models.CharField(max_length=40)),
                ("DRIVING_EXPERIENCE", models.IntegerField()),
                ("CAR_OWNERSHIP", models.BooleanField()),
                ("CLAIMS", models.BooleanField()),
            ],
        ),
    ]
