# Generated by Django 4.2.6 on 2023-10-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matching",
            old_name="Domains",
            new_name="Domain",
        ),
    ]
