# Generated by Django 4.2.6 on 2023-11-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="Rating",
            field=models.IntegerField(default=0),
        ),
    ]
