# Generated by Django 4.2.6 on 2023-10-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_rename_domains_matching_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matching",
            name="Career_objectives",
            field=models.CharField(max_length=100),
        ),
    ]
