# Generated by Django 4.2.6 on 2023-11-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_mentor_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingrequest",
            name="available_dates",
            field=models.ManyToManyField(to="register.disponibilite"),
        ),
        migrations.AddField(
            model_name="notification",
            name="coaching_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="register.coachingrequest",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
