# Generated by Django 4.2.6 on 2023-11-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferences",
            name="language",
        ),
        migrations.AlterField(
            model_name="preferences",
            name="display_panel",
            field=models.BooleanField(default=False),
        ),
    ]
