# Generated by Django 4.2.6 on 2023-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_userprofile_mentor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
    ]
